#!/usr/bin/env node
import {action,getState} from './service.mjs';
import {getKey,readProfile} from './storage.mjs';
import {syncAll} from './weread.mjs';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { readFileSync, existsSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
async function api(path,mode='live',body){if(path==='state')return getState(mode);return action('/api/'+path,mode,body||{});}
const server=new McpServer({name:'reading-buddy',version:'1.1.0'});
const mode=z.enum(['live','demo']).default('live').describe('live 为个人数据，demo 为独立的虚构示例。');
const respond=fn=>async(args)=>{try{const d=await fn(args);return {content:[{type:'text',text:JSON.stringify(d)}],structuredContent:d};}catch(e){return {isError:true,content:[{type:'text',text:e.message}]};}};
const readOnly={readOnlyHint:true,destructiveHint:false,openWorldHint:false};
server.registerTool('reading_open_dashboard',{title:'打开阅读看板',description:'在 WorkBuddy 内打开完整本地阅读看板，不启动HTTP服务。此工具只向模型返回简要概览；界面数据通过仅界面可见的工具获取。',inputSchema:{mode},annotations:readOnly,_meta:{ui:{resourceUri:'ui://reading-buddy/dashboard.html'}}},respond(async({mode})=>{
 if(mode==='live'&&getKey()&&!readProfile().snapshot)void syncAll();
 const d=await api('state',mode),book=d.snapshot?.books.find(b=>b.id===d.settings.primaryBookId),weekly=d.snapshot?.weekly;
 return {mode,today:d.today,localOnly:true,connected:d.connection.connected,syncedAt:d.snapshot?.syncedAt||null,sync:d.sync,goal:d.settings.goal,primaryBook:book?{id:book.id,title:book.title,author:book.author,progress:book.progress}:null,todaySeconds:weekly?.end===d.today?(weekly.days[d.today]??null):null,weeklySeconds:weekly?.end===d.today?weekly.totalSeconds:null,counts:d.snapshot?.totals||null};
}));
server.registerResource('reading-dashboard','ui://reading-buddy/dashboard.html',{mimeType:'text/html;profile=mcp-app',description:'读书搭子的内嵌阅读概览'},async()=>({contents:[{uri:'ui://reading-buddy/dashboard.html',mimeType:'text/html;profile=mcp-app',text:readFileSync(existsSync(join(dirname(fileURLToPath(import.meta.url)),'dashboard.html'))?join(dirname(fileURLToPath(import.meta.url)),'dashboard.html'):join(root,'dist/mcp/dashboard.html'),'utf8'),_meta:{ui:{csp:{connectDomains:[],resourceDomains:['https://*.qpic.cn','https://*.qq.com','https://*.qlogo.cn']}}}}]}));
server.registerTool('reading_search_books',{title:'查找我的书',description:'按书名或作者查询已同步电子书。返回分页结果；total 为本次筛选后的电子书数，不含有声书与文章收藏。',inputSchema:{mode,query:z.string().max(200).default(''),status:z.enum(['all','reading','finished']).default('all'),offset:z.number().int().min(0).default(0),limit:z.number().int().min(1).max(30).default(15)},annotations:readOnly},respond(async({mode,query,status,offset,limit})=>{const d=await api('state',mode),books=(d.snapshot?.books||[]).filter(b=>(b.title+b.author).toLowerCase().includes(query.toLowerCase())&&(status==='all'||(status==='finished'?b.done:!b.done)));return {total:books.length,books:books.slice(offset,offset+limit).map(({id,title,author,progress,done,deepLink})=>({id,title,author,progress,done,deepLink})),nextOffset:offset+limit<books.length?offset+limit:null};}));
server.registerTool('reading_get_notes',{title:'回顾一本书的笔记',description:'只读取指定书籍的个人划线和想法。refresh=true 从微信读书更新该书内容。返回最多30条，使用offset继续读取，勿将部分内容声称为全库。',inputSchema:{mode,bookId:z.string().max(120),refresh:z.boolean().default(false),offset:z.number().int().min(0).default(0),limit:z.number().int().min(1).max(30).default(15)},annotations:{...readOnly,openWorldHint:true}},respond(async({mode,bookId,refresh,offset,limit})=>{if(refresh)await api('notes',mode,{bookId});const d=await api('state',mode),rows=(d.snapshot?.notes||[]).filter(n=>n.bookId===bookId);return {totalLoaded:rows.length,notes:rows.slice(offset,offset+limit),nextOffset:offset+limit<rows.length?offset+limit:null};}));
server.registerTool('reading_prepare_card',{title:'准备读书卡片',description:'仅提取用户选择的笔记形成带来源的本机草稿。可据此在WorkBuddy润色；不得伪造原文和用户经历。先向用户展示，明确要求保存后再调用reading_save_card。',inputSchema:{mode,noteIds:z.array(z.string()).min(1).max(20),reflection:z.string().max(10000).default('')},annotations:readOnly},respond(async({mode,noteIds,reflection})=>api('draft',mode,{noteIds,reflection})));
server.registerTool('reading_prepare_review',{title:'准备阅读复盘',description:'读取本周或本月数据，返回可编辑复盘草稿；缺数据时保留缺口，不能补造阅读量或心得。',inputSchema:{mode,period:z.enum(['weekly','monthly']).default('weekly')},annotations:readOnly},respond(async({mode,period})=>api('review',mode,{period})));
server.registerTool('reading_save_card',{title:'保存确认后的卡片',description:'保存用户已确认的读书卡片或复盘到本机。仅在用户明确要求保存该内容后使用，confirmed必须为true。不会向微信读书发布。',inputSchema:{mode,confirmed:z.literal(true),title:z.string().min(1).max(200),body:z.string().min(1).max(100000),kind:z.enum(['card','weekly','monthly']).default('card'),noteIds:z.array(z.string()).max(100).default([])},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false}},respond(async({mode,confirmed,...card})=>{const d=await api('cards',mode,{...card,origin:'workbuddy'});return {id:d.id,title:d.title,savedAt:d.updatedAt,localOnly:true,view:d.kind==='card'?'notes':'review'};}));
const uiResult=fn=>async args=>{try{return {content:[{type:'text',text:'本地界面操作完成。'}],_meta:{readingData:await fn(args)}};}catch(e){return {isError:true,content:[{type:'text',text:e instanceof z.ZodError?'数据格式不正确。':e.message}]};}};
server.registerTool('reading_ui_state',{description:'仅供本地看板获取界面状态。书架、笔记和卡片仅放入UI元数据，不写入模型可见文本。',inputSchema:{mode},annotations:readOnly,_meta:{ui:{visibility:['app']}}},uiResult(async({mode})=>getState(mode)));
server.registerTool('reading_ui_action',{description:'仅供用户在看板中点击操作。凭证不能通过此工具传入。',inputSchema:{mode,operation:z.enum(['settings','sync','book','notes','reflection','draft','prepare-workbuddy','review','cards','import','export']),payload:z.unknown().optional()},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:true},_meta:{ui:{visibility:['app']}}},uiResult(async({mode,operation,payload})=>operation==='export'?readProfile(mode):action('/api/'+operation,mode,payload||{})));
await server.connect(new StdioServerTransport());
