import {embedded,readMode,storeMode,readState,perform,downloadText,sendToWorkBuddy,openReadingLink} from './transport.js';
import React, {useCallback,useEffect,useRef,useState} from 'react';
import {BookOpen,House,Books,Notebook,ChartBar,GearSix,ArrowsClockwise,ArrowRight,Leaf,WarningCircle,CircleNotch,CheckCircle,FloppyDisk,DownloadSimple,Sparkle,Copy,ArrowSquareOut} from '@phosphor-icons/react';
import {Modal,stamp,exportText} from './components.jsx';
import {Today,Shelf,Notes,Review} from './views.jsx';
import {Settings} from './settings.jsx';
const nav=[['today','今日阅读',House],['shelf','我的书架',Books],['notes','笔记回顾',Notebook],['review','阅读复盘',ChartBar]];
export function App(){
 const [page,setPage]=useState(nav.some(n=>n[0]===location.hash.slice(1))?location.hash.slice(1):'today');
 const [mode,setMode]=useState(readMode);
 const [data,setData]=useState(null),[error,setError]=useState(''),[toast,setToast]=useState(''),[busy,setBusy]=useState(''),[settings,setSettings]=useState(false),[draft,setDraft]=useState(null),[prompt,setPrompt]=useState(null),[query,setQuery]=useState(''),[noteBook,setNoteBook]=useState('all');
 const csrf=useRef(''),currentMode=useRef(mode);currentMode.current=mode;
 const load=useCallback(async()=>{const m=mode;try{const d=await readState(m);if(m!==currentMode.current)return;csrf.current=d.csrf;setData(d);}catch(e){setError(e.message||'页面数据加载失败，请重试。');}},[mode]);
 useEffect(()=>{setData(null);load();},[load]);
 useEffect(()=>{if(!data?.sync.running||mode==='demo')return;const t=setInterval(load,1500);return()=>clearInterval(t);},[data?.sync.running,mode,load]);
 useEffect(()=>{const fn=()=>setPage(nav.some(n=>n[0]===location.hash.slice(1))?location.hash.slice(1):'today');window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn);},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(t);},[toast]);
 const request=(path,body={})=>perform(path,mode,body);
 const act=async(name,fn)=>{setBusy(name);setError('');try{await fn();await load();return true;}catch(e){setError(e.message||'操作未完成，请重试。');return false;}finally{setBusy('');}};
 const go=p=>{setPage(p);setQuery('');location.hash=p;window.scrollTo(0,0);};
 const changeMode=m=>{storeMode(m);currentMode.current=m;setMode(m);setNoteBook('all');setQuery('');setError('');setSettings(false);setDraft(null);};
 useEffect(()=>{if(!embedded)return;const f=e=>changeMode(e.detail);window.addEventListener('reading-host-mode',f);return()=>window.removeEventListener('reading-host-mode',f);},[]);
 const a={embedded,data,mode,busy,error,query,setQuery,noteBook,setNoteBook,go,act,request,notify:setToast,setDraft,setPrompt,openSettings:()=>setSettings(true),changeMode};
 const today=data?.today||new Date().toISOString().slice(0,10);
 const stateLabel=mode==='demo'?'示例书架 · 可自由体验':data?.sync.running?data.sync.stage:data?.sync.error?'同步待重试':data?.snapshot?'微信读书 · '+stamp(data.snapshot.syncedAt)+' 更新':'连接后，开始你的阅读';
 return <div className="app-shell"><aside className="sidebar"><a href="#today" className="brand" onClick={()=>go('today')}><BookOpen size={38} weight="duotone"/><span><strong>读书搭子</strong><small>微信读书伴侣</small></span></a><nav aria-label="主导航">{nav.map(([id,label,Icon])=><button key={id} className={page===id?'nav-active':''} aria-current={page===id?'page':undefined} onClick={()=>go(id)}><Icon size={23} weight={page===id?'fill':'regular'}/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><button className="settings-link" onClick={()=>setSettings(true)}><GearSix size={22}/><span>设置与连接</span></button><p>让阅读<br/>成为生活的一部分。</p><div className="little-line"/></div></aside>
 <main className="main"><header className="topbar"><span className="top-date">{new Date(today+'T12:00:00').toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}</span><div className="top-rule"/><button className="sync-state" onClick={()=>setSettings(true)}><span className={'status-dot '+(data?.sync.error?'warning':'')}/><span>{stateLabel}</span></button><button className={'icon-button '+(data?.sync.running?'rotating':'')} disabled={!!busy||data?.sync.running||!data?.connection.connected||mode==='demo'} aria-label="同步微信读书" onClick={()=>act('sync',()=>request('sync'))}><ArrowsClockwise size={19}/></button></header>
 {mode==='demo'&&<div className="demo-ribbon"><span><Leaf size={17}/>示例体验 · 虚构书籍与数据</span><button onClick={()=>changeMode('live')}>回到我的阅读 <ArrowRight size={16}/></button></div>}
 {(error||data?.sync.error)&&<div className="notice" role="alert"><WarningCircle size={20}/><span>{error||data.sync.error}</span><button onClick={()=>act('retry',()=>request('sync'))} disabled={!!busy||data?.sync.running}>重试</button></div>}
 {!data?<div className="loading"><CircleNotch className="spin" size={32}/><p>正在打开你的书房…</p><button className="text-button" onClick={load}>重新加载</button></div>:<>{page==='today'?<Today a={a}/>:page==='shelf'?<Shelf a={a}/>:page==='notes'?<Notes a={a}/>:<Review a={a}/>} {!!data.snapshot?.warnings.length&&<details className="data-notes"><summary><WarningCircle size={16}/>数据说明 · {data.snapshot.warnings.length} 项</summary>{data.snapshot.warnings.map((w,i)=><p key={i}>{w}</p>)}</details>}<footer className="page-footer"><span>读书搭子 <span className="footer-dot">/</span> 让读过的留下来</span><span>{mode==='demo'?'示例数据独立保存':'个人数据保存在本机'}</span></footer></>}
 </main><nav className="mobile-nav" aria-label="移动导航">{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>go(id)}><Icon size={23} weight={page===id?'fill':'regular'}/><span>{label}</span></button>)}<button onClick={()=>setSettings(true)} aria-label="设置"><GearSix size={22}/><span>设置</span></button></nav>
 {toast&&<div className="toast" role="status"><CheckCircle size={21} weight="fill"/>{toast}</div>}
 {settings&&data&&<Settings a={a} onClose={()=>setSettings(false)}/>}
 {draft&&<Modal title={draft.id?'编辑已保存内容':'让这次阅读，留在纸上'} onClose={()=>setDraft(null)} wide>{error&&<p className="inline-error" role="alert">{error}</p>}<div className="draft-meta"><span>{draft.origin==='workbuddy'?'WorkBuddy 草稿':'本机整理 · 可自由编辑'}</span><span>确认后保存</span></div><label className="field">标题<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} maxLength={200}/></label><label className="field">卡片内容<textarea className="draft-textarea" value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})} maxLength={100000}/></label><div className="modal-actions"><button className="primary" disabled={!!busy||!draft.title.trim()||!draft.body.trim()} onClick={()=>act('save',async()=>{const saved=await request('cards',{id:draft.id,title:draft.title,body:draft.body,kind:draft.kind,noteIds:draft.noteIds||[],origin:draft.origin||'local'});setDraft({...saved,reflection:draft.reflection});setToast('已保存到本机，随时回来继续编辑。');})}><FloppyDisk size={18}/>保存卡片</button><button className="outline" disabled={!!busy} onClick={()=>act('export',()=>downloadText(draft.title.replace(/[/\\:*?"<>|]/g,'-')+'.md',draft.body))}><DownloadSimple size={18}/>导出 Markdown</button>{draft.kind==='card'&&<button className="text-button" disabled={!!busy} onClick={()=>act('workbuddy',async()=>{const prepared=await request('prepare-workbuddy',{noteIds:draft.noteIds,reflection:draft.reflection||''});setPrompt({title:'在 WorkBuddy 中继续',text:prepared.prompt});})}><Sparkle size={18}/>交给 WorkBuddy</button>}</div></Modal>}
 {prompt&&<Modal title={prompt.title} onClose={()=>setPrompt(null)}><p className="muted">{prompt.book?'当前接口没有返回阅读链接，复制书名后前往微信读书。':embedded?'确认发送后，WorkBuddy 会读取这些选定笔记用于模型处理；不会读取整个笔记库。':'复制任务到已连接读书搭子的 WorkBuddy。只有所选笔记会用于生成，不会发送整个书架。'}</p><textarea className="handoff-prompt" aria-label="接续任务" readOnly value={prompt.text}/><div className="modal-actions">{embedded&&!prompt.book&&<button className="primary" onClick={()=>act('send',async()=>{await sendToWorkBuddy(prompt.text);setPrompt(null);setToast('任务已交给 WorkBuddy。');})}><Sparkle size={18}/>确认发送给 WorkBuddy</button>}<button className="primary" onClick={()=>act('copy',async()=>{await navigator.clipboard.writeText(prompt.text);setToast('已复制。');})}><Copy size={18}/>复制{prompt.book?'书名':'任务'}</button>{prompt.book&&<button className="outline" onClick={()=>act('link',()=>openReadingLink('https://weread.qq.com/'))}>打开微信读书 <ArrowSquareOut size={18}/></button>}</div></Modal>}
 </div>;
}
