import {assetUrl} from './transport.js';
import React,{useEffect,useRef,useState} from 'react';
import {BookOpen,X,Notebook,ArrowRight} from '@phosphor-icons/react';
export const fmt=s=>s==null?'暂不可用':`${Math.floor(s/3600)?Math.floor(s/3600)+'小时':''}${Math.floor(s%3600/60)}分钟`;
export const shift=(d,n)=>new Date(Date.parse(d+'T12:00:00Z')+n*864e5).toISOString().slice(0,10);
export const stamp=v=>v?new Date(v).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}):'尚未同步';
export const short=t=>(t||'').replace(/（.*?）/g,'').trim();
export function exportText(name,text,type='text/markdown;charset=utf-8'){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
export function Cover({book,hero=false}){const [broken,setBroken]=useState(false);useEffect(()=>setBroken(false),[book?.cover]);return book?.cover&&!broken?<img className={'book-cover '+(hero?'hero-cover':'')} src={assetUrl(book.cover)} alt={'《'+book.title+'》封面'} loading={hero?'eager':'lazy'} referrerPolicy="no-referrer" onError={()=>setBroken(true)}/>:<div className={'cover-unavailable '+(hero?'hero-cover':'')}><BookOpen size={42} weight="light"/><span>封面待同步</span></div>;}
export function Modal({title,onClose,children,wide=false}){const ref=useRef();useEffect(()=>{const d=ref.current;d.showModal();return()=>d.close();},[]);return <dialog ref={ref} className={'modal '+(wide?'modal-wide':'')} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label="关闭弹窗" onClick={onClose}><X size={22}/></button></div>{children}</dialog>;}
export function Intro({eyebrow,title,subtitle}){return <div className="page-intro">{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1><p>{subtitle}</p></div>;}
export function Rhythm({period,today,goal,expanded=false}){const dow=new Date(today+'T12:00:00Z').getUTCDay(),start=shift(today,-((dow+6)%7));const days=expanded&&period?.start?Array.from({length:Math.round((Date.parse(period.end)-Date.parse(period.start))/864e5)+1},(_,i)=>shift(period.start,i)):Array.from({length:7},(_,i)=>shift(start,i));const vals=days.map(d=>period?.days?.[d]??null),max=Math.max(goal*60,...vals.filter(v=>v!==null));return <div className={'rhythm '+(expanded?'expanded-chart':'')}><div className="chart-area" role="img" aria-label={days.map((d,i)=>d+' '+(d>today?'未到日期':fmt(vals[i]))).join('；')}><div className="chart-guide"><span>{Math.round(max/60)} 分钟</span><span>0</span></div><div className="bar-row">{days.map((d,i)=><div className={'bar-column '+(d===today?'is-today':'')} key={d}><div className="bar-track" title={d+'：'+(d>today?'未到日期':fmt(vals[i]))}><div className={'bar '+(vals[i]===null?'unknown':'')} style={{height:vals[i]===null?'8px':Math.max(2,vals[i]/max*100)+'%'}}/></div><span>{Number(d.slice(5,7))}/{Number(d.slice(8))}</span>{!expanded&&<small>{['周一','周二','周三','周四','周五','周六','周日'][i]}</small>}</div>)}</div></div><p className="chart-caption">总时长含阅读与收听 · 虚线表示尚无明细</p></div>;}
export function SavedCards({cards,onOpen}){if(!cards.length)return null;return <section className="saved-section"><h2><Notebook size={22}/>已经留下的阅读记录</h2><div className="saved-list">{cards.map(c=><button key={c.id} onClick={()=>onOpen(c)}><span><strong>{c.title}</strong><small>{stamp(c.updatedAt)} · {c.origin==='workbuddy'?'WorkBuddy':'本机整理'}</small></span><ArrowRight size={20}/></button>)}</div></section>;}
