import {embedded,exportBackup} from './transport.js';
import React,{useRef,useState} from 'react';
import {PlugsConnected,Check,DownloadSimple,UploadSimple,ArrowRight,CircleNotch} from '@phosphor-icons/react';
import {Modal} from './components.jsx';
export function Settings({a,onClose}){const {data,mode,busy,error,changeMode,request,act,notify}=a,[goal,setGoal]=useState(data.settings.goal),[zone,setZone]=useState(data.settings.timeZone),[key,setKey]=useState(''),[persist,setPersist]=useState(false),[importFile,setImportFile]=useState(''),[importData,setImportData]=useState(null),[localError,setLocalError]=useState(''),input=useRef();
 const choose=async e=>{setLocalError('');const f=e.target.files?.[0];if(!f)return;try{if(f.size>25*1024*1024)throw Error('文件不能超过25MB。');const d=JSON.parse(await f.text());if(d.schema!==1||!Array.isArray(d.cards)||!Array.isArray(d.reflections))throw Error('请选择读书搭子导出的备份。');if(d.mode!==mode)throw Error('备份的数据模式不一致，请先切换对应模式。');setImportData(d);setImportFile(f.name);}catch(e){setLocalError(e.message);}};
 return <Modal title="设置与连接" onClose={onClose}>{error&&<p className="inline-error" role="alert">{error}</p>}<section className="settings-section"><h3><PlugsConnected size={21}/>微信读书连接</h3><p className="muted">{data.connection.connected?'已配置个人凭证。阅读数据保存在这台电脑上。':'连接后即可同步自己的电子书、阅读时长和笔记。'}</p>{embedded?<div className="local-auth-info"><p>微信读书授权由 WorkBuddy 的本地连接器管理。请在连接器设置中填写个人 API Key，然后重新连接。</p><p>授权不会经过这个页面或模型对话。书架、卡片和回顾保存在本机；调用云端模型时，选中的笔记可能用于模型处理。</p></div>:<><label className="field">个人 API Key<input type="password" autoComplete="off" placeholder="wrk-…" value={key} onChange={e=>setKey(e.target.value)}/></label><label className="checkbox"><input type="checkbox" checked={persist} onChange={e=>setPersist(e.target.checked)}/>将此凭证保存在本机，下次启动继续使用</label><p className="small muted">仅保存在本机受限文件中，不包含在导出备份里。WorkBuddy 模型只在你发起任务时读取选定内容。</p><div className="setting-actions"><button className="primary" disabled={!!busy||!key.trim()||data.sync.running} onClick={()=>act('connect',async()=>{await request('connect',{key:key.trim(),persist});setKey('');notify('连接成功，正在同步你的阅读。');})}>{busy==='connect'?<CircleNotch size={18} className="spin"/>:<PlugsConnected size={18}/>}验证并连接</button>{data.connection.connected&&<button className="text-button" disabled={!!busy||data.sync.running} onClick={()=>act('disconnect',async()=>{await request('disconnect');notify('已断开连接，原账户记录仍保存在本机。');})}>断开连接</button>}</div></>}</section>
 <section className="settings-section"><h3>给阅读留一点时间</h3><div className="goal-options">{[15,30,60].map(g=><button key={g} className={goal===g?'selected':''} onClick={()=>setGoal(g)}>{g} 分钟</button>)}<input aria-label="自定义目标分钟" type="number" min="5" max="600" value={goal} onChange={e=>setGoal(Number(e.target.value))}/></div><label className="field">统计时区<select value={zone} onChange={e=>setZone(e.target.value)}>{[...new Set([data.settings.timeZone,'Asia/Shanghai','Asia/Hong_Kong','Asia/Tokyo','Europe/London','America/New_York','America/Los_Angeles'])].map(z=><option key={z}>{z}</option>)}</select></label><button className="outline" disabled={!!busy||goal<5||goal>600} onClick={()=>act('settings',async()=>{await request('settings',{...data.settings,goal,timeZone:zone});notify('阅读目标已保存。');})}><Check size={18}/>保存偏好</button></section>
 <section className="settings-section"><h3>我的数据</h3><p className="muted">导入会合并卡片和回顾，保留更新的版本，并先备份当前数据。</p><div className="setting-actions"><button className="outline" disabled={!!busy} onClick={()=>act('export',()=>exportBackup(mode))}><DownloadSimple size={18}/>导出完整备份</button><button className="outline" onClick={()=>input.current.click()}><UploadSimple size={18}/>选择备份文件</button><input ref={input} type="file" accept="application/json,.json" hidden onChange={choose}/></div>{localError&&<p className="inline-error" role="alert">{localError}</p>}{importData&&<div className="import-preview"><strong>{importFile}</strong><p>{importData.cards.length} 张卡片 · {importData.reflections.length} 次回顾</p><button className="primary" disabled={!!busy} onClick={()=>act('import',async()=>{await request('import',importData);setImportData(null);notify('备份已合并，原记录已保留。');})}>合并导入</button></div>}</section>
 <section className="settings-section"><h3>看看另一种阅读日常</h3><p className="muted">示例数据与个人数据分开保存，切换不会改变你的阅读记录。</p><button className="text-button" onClick={()=>changeMode(mode==='demo'?'live':'demo')}>{mode==='demo'?'回到我的阅读':'体验示例书房'}<ArrowRight size={18}/></button></section></Modal>;
}
