import {assetUrl,readState,openReadingLink} from './transport.js';
import React,{useState,useEffect} from 'react';
import {BookOpen,Books,Notebook,ChartBar,Quotes,PencilLine,ArrowsClockwise,ArrowRight,CaretRight,Check,CheckCircle,Leaf,FloppyDisk,Sparkle,MagnifyingGlass,PlugsConnected,CircleNotch} from '@phosphor-icons/react';
import {Cover,Intro,Rhythm,SavedCards,fmt,short,stamp} from './components.jsx';
export function Today({a}){
 const {data,mode,busy,go,act,request,notify,setPrompt,openSettings,changeMode}=a,books=data.snapshot?.books||[],notes=data.snapshot?.notes||[],today=data.today,weekly=data.snapshot?.weekly,goal=data.settings.goal;
 const [noteIndex,setNoteIndex]=useState(0),note=notes[noteIndex%Math.max(notes.length,1)],book=books.find(b=>b.id===data.settings.primaryBookId)||books[0];
 const mins=weekly?.end===today&&weekly.days[today]!=null?Math.floor(weekly.days[today]/60):null,gap=mins===null?goal:Math.max(0,goal-mins);
 const open=()=>act('open',async()=>{if(mode==='demo'){notify('这是示例书籍。连接微信读书后，即可继续读自己的书。');return;}await request('book',{id:book.id});const d=await readState('live'),link=d.snapshot?.books.find(b=>b.id===book.id)?.deepLink;if(link)await openReadingLink(link);else setPrompt({title:'继续阅读',book:true,text:book.title});});
 return <><Intro title="今天，给自己留一段专注时间" subtitle="在书页之间，遇见更大的自己。"/>
 {book?<section className="reading-hero"><img className="hero-background" src={assetUrl('/assets/reading-light.png')} alt=""/><div className="hero-book"><Cover book={book} hero/><div className="hero-book-caption">当前主读 <span>01</span></div></div><div className="hero-copy"><div className="hero-meta"><p className="eyebrow">TODAY’S READING</p><h2 className="hero-title" title={book.title}>{short(book.title)}</h2><p className="author">{book.author||'作者信息待同步'}</p></div><div className="hero-content"><h3>{mins===null?<>给自己 {goal} 分钟，<br/>慢慢进入一本书。</>:gap?<>再读 {gap} 分钟，<br/>给今天一个留白。</>:<>今天的阅读，<br/>已经好好留下。</>}</h3><div className="progress-caption"><span>阅读进度</span><strong>{book.done?'已读完':book.progress===null?'待同步':book.progress+'%'}</strong></div><div className="progress-track"><span style={{width:(book.progress??0)+'%'}}/></div><p className="muted small">{mins===null?'今日时长待同步':`今日已读 ${mins} 分钟`}<span className="middot">·</span>每日目标 {goal} 分钟</p><div className="hero-actions"><button className="primary" disabled={!!busy} onClick={open}>{busy==='open'?<CircleNotch className="spin" size={20}/>:<BookOpen size={21}/>}打开微信读书</button><button className="text-button" onClick={()=>go('shelf')}><ArrowsClockwise size={18}/>换一本</button></div></div></div><p className="hero-poem">好的书，<br/>会在平凡的日子里<br/>给你一点光。</p></section>:<section className="welcome reading-hero"><img className="hero-background" src={assetUrl('/assets/reading-light.png')} alt=""/><div><p className="eyebrow">YOUR READING COMPANION</p><h2>你的书房，<br/>从连接开始。</h2><p>{data.sync.running?'正在整理你的书架，稍后将自动显示。':'把微信读书里的阅读、划线与想法，带到这里。'}</p><div className="hero-actions"><button className="primary" onClick={openSettings}><PlugsConnected size={20}/>连接微信读书</button><button className="text-button" onClick={()=>changeMode('demo')}>先体验示例 <ArrowRight size={18}/></button></div></div></section>}
 <div className="today-support"><section className="rhythm-section"><div className="section-heading"><div><h2><ChartBar weight="fill" size={22}/>本周阅读节奏</h2><p>从一点一滴的阅读里，看见积累的力量。</p></div><button className="stat-link" onClick={()=>go('review')}><strong>{weekly?.end===today?fmt(weekly.totalSeconds):'待同步'}</strong><span>本周累计阅读时长 <CaretRight size={13}/></span></button></div><Rhythm period={weekly} today={today} goal={goal}/></section><section className="thought-section"><div className="section-heading"><div><h2><Notebook weight="fill" size={22}/>留住一个想法</h2><p>随手记录，让阅读真正留下痕迹。</p></div><button className="text-button small" disabled={!notes.length} onClick={()=>setNoteIndex(noteIndex+1)}><ArrowsClockwise size={16}/>换一条</button></div>{note?<><blockquote><Quotes weight="fill" size={30}/><p>{(note.thought||note.quote).slice(0,170)}{(note.thought||note.quote).length>170?'…':''}</p></blockquote><p className="quote-source">— 《{short(note.title)}》{note.type==='thought'?' · 我的想法':' · 划线'}</p><button className="outline" onClick={()=>{a.setNoteBook(note.bookId);go('notes');}}><PencilLine size={19}/>生成读书卡片</button></>:<div className="empty-inline"><p>留下一条划线，让想法在这里重逢。</p><button className="outline" onClick={()=>go('notes')}>查看笔记 <ArrowRight size={17}/></button></div>}</section></div></>;
}
export function Shelf({a}){const {data,query,setQuery,busy,act,request,notify,go,setNoteBook}=a,[filter,setFilter]=useState('reading'),[limit,setLimit]=useState(12),books=data.snapshot?.books||[];
 const filtered=books.filter(b=>filter==='all'||(filter==='finished'?b.done:filter==='unread'?!b.done&&b.progress===0:!b.done&&(b.progress>0||b.id===data.settings.primaryBookId))).filter(b=>(b.title+b.author).toLowerCase().includes(query.toLowerCase()));
 return <><Intro eyebrow="YOUR PRIVATE LIBRARY" title="把书架，变成下一次出发。" subtitle="接着读熟悉的那本，也为新的好奇留一点位置。"/><div className="toolbar"><div className="tabs" aria-label="书架筛选">{[['reading','继续阅读'],['unread','未开始'],['finished','已读完'],['all','全部电子书']].map(([id,label])=><button key={id} aria-pressed={filter===id} className={filter===id?'active':''} onClick={()=>{setFilter(id);setLimit(12);}}>{label}</button>)}</div><label className="search"><MagnifyingGlass size={18}/><input aria-label="搜索书名或作者" placeholder="搜索书名或作者" value={query} onChange={e=>{setQuery(e.target.value);setLimit(12);}}/></label></div><p className="count-caption">{filtered.length} 本电子书{data.snapshot?.totals.albums>0?` · 另有 ${data.snapshot.totals.albums} 个有声书/专辑`:''}{data.snapshot?.totals.articles>0?' · 1 个文章收藏入口':''} · 有声书与文章收藏暂不在下方展开</p>
 {filtered.length?<div className="book-grid">{filtered.slice(0,limit).map(b=><article className="shelf-book" key={b.id}><button className="cover-button" aria-label={'查看《'+b.title+'》的笔记'} onClick={()=>{setNoteBook(b.id);go('notes');}}><Cover book={b}/>{data.settings.primaryBookId===b.id&&<span className="primary-tag"><Check size={13}/>主读中</span>}</button><h2 title={b.title}>{short(b.title)}</h2><p>{b.author||'作者待同步'}</p><div className="book-progress"><div className="progress-track"><span style={{width:(b.progress??0)+'%'}}/></div><span>{b.done?'读完':b.progress===null?'—':b.progress+'%'}</span></div><div className="book-row-actions"><button className={data.settings.primaryBookId===b.id?'outline':'text-button'} disabled={!!busy||data.settings.primaryBookId===b.id} onClick={()=>act('primary',async()=>{await request('settings',{...data.settings,primaryBookId:b.id});notify('已将《'+short(b.title)+'》设为主读。');})}>{data.settings.primaryBookId===b.id?<><Check size={16}/>当前主读</>:<>设为主读 <ArrowRight size={16}/></>}</button>{b.weeklySeconds!==null&&<small>本周 {fmt(b.weeklySeconds)}</small>}</div></article>)}</div>:<div className="empty"><Books size={42} weight="light"/><h2>{query?'没有找到这本书':'这里还没有书籍'}</h2><p>{query?'换一个书名或作者试试。':'连接微信读书后，你的书架会出现在这里。'}</p><button className="outline" onClick={()=>query?setQuery(''):a.openSettings()}>{query?'清除搜索':'查看连接'}</button></div>}{filtered.length>limit&&<button className="load-more outline" onClick={()=>setLimit(limit+12)}>再看 12 本 <ArrowRight size={18}/></button>}</>;
}
export function Notes({a}){const {data,mode,noteBook,setNoteBook,busy,act,request,notify,setDraft}=a,[selected,setSelected]=useState(null),[reflection,setReflection]=useState(''),[noteLimit,setNoteLimit]=useState(80);const books=data.snapshot?.books||[],choices=[...new Map([books.find(b=>b.id===noteBook),...books.slice(0,100)].filter(Boolean).map(b=>[b.id,b])).values()],notes=(data.snapshot?.notes||[]).filter(n=>noteBook==='all'||n.bookId===noteBook),note=notes.find(n=>n.id===selected)||notes[0];
 useEffect(()=>setReflection(data.reflections.find(r=>r.noteId===note?.id)?.text||''),[note?.id,mode]);
 const pick=n=>{setSelected(n.id);setReflection(data.reflections.find(r=>r.noteId===n.id)?.text||'');};
 return <><Intro eyebrow="READ. REFLECT. REMEMBER." title="读过的，慢慢变成自己的。" subtitle="从一条划线，开始今天的回顾。"/><div className="toolbar notes-toolbar"><label className="select-label"><Books size={18}/><select aria-label="选择笔记书籍" value={noteBook} onChange={e=>{setNoteBook(e.target.value);setSelected(null);}}><option value="all">所有已载入笔记</option>{choices.map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select></label><button className="outline" disabled={!!busy||noteBook==='all'||mode==='demo'} onClick={()=>act('notes',async()=>{const r=await request('notes',{bookId:noteBook});notify(`已载入 ${r.count} 条笔记。`);})}>{busy==='notes'?<CircleNotch className="spin" size={17}/>:<ArrowsClockwise size={17}/>}同步这本书的笔记</button></div><p className="count-caption">已载入 {notes.length} 条内容 · 笔记总数包含划线、想法和书签；书签仅提供数量</p>
 <div className="reflection-layout"><section className="notes-list"><h2><Notebook size={22}/>今日回顾 <span>{notes.length} 条笔记</span></h2>{notes.length?notes.slice(0,noteLimit).map(n=><button key={n.id} className={'note-row '+(note?.id===n.id?'selected':'')} onClick={()=>pick(n)}><Quotes size={22} weight="fill"/><div><p className="note-text">{n.quote||n.thought}</p>{n.quote&&n.thought&&<p className="original-thought">我的想法：{n.thought}</p>}<small>《{short(n.title)}》{n.chapter?' · '+n.chapter:''}</small><span className="note-date">{n.date||'日期待同步'} · {n.type==='thought'?'想法':'划线'}</span></div><CaretRight size={16}/></button>):<div className="empty"><Notebook size={36} weight="light"/><h3>让一个想法留下来</h3><p>在上方选择书籍，载入其中的划线和想法。</p></div>}{notes.length>noteLimit&&<button className="outline load-more" onClick={()=>setNoteLimit(noteLimit+80)}>再看 80 条笔记 <ArrowRight size={16}/></button>}</section><section className="reflection-editor"><h2><PencilLine size={27}/>你为什么留下这句话？</h2><textarea aria-label="我的理解" maxLength={10000} placeholder="写一句自己的理解，也可以联系最近的一件事…" value={reflection} onChange={e=>setReflection(e.target.value)} disabled={!note}/><span className="character-count">{reflection.length} / 10000</span><button className="primary full" disabled={!!busy||!note} onClick={()=>act('draft',async()=>{if(reflection.trim())await request('reflection',{noteId:note.id,text:reflection});setDraft({...await request('draft',{noteIds:[note.id],reflection}),reflection});})}><Sparkle size={20}/>生成我的读书卡片</button><div className="editor-actions"><button className="text-button" disabled={!!busy||!note} onClick={()=>act('reflection',async()=>{await request('reflection',{noteId:note.id,text:reflection});notify('这次回顾已保存。');})}><FloppyDisk size={18}/>保存这次回顾</button><button className="text-button" disabled={!notes.length} onClick={()=>pick(notes[(notes.findIndex(n=>n.id===note?.id)+1)%notes.length])}><ArrowsClockwise size={18}/>换一条</button></div><p className="editor-note">先在本机整理成可编辑草稿。<br/>需要 AI 润色时，可将选中的内容交给 WorkBuddy。</p></section></div><SavedCards cards={data.cards.filter(c=>c.kind==='card')} onOpen={setDraft}/></>;
}
export function Review({a}){const {data,busy,act,request,setDraft,go}=a,[period,setPeriod]=useState('weekly'),stats=data.snapshot?.[period],today=data.today,valid=stats?.end===today,finished=(data.snapshot?.books||[]).filter(b=>b.finishDate&&b.finishDate>=(stats?.start||today)&&b.finishDate<=today);
 return <><Intro eyebrow="YOUR READING JOURNEY" title="每一页，都算数。" subtitle="看见阅读的节奏，也留住真正触动你的事。"/><div className="toolbar"><div className="tabs"><button className={period==='weekly'?'active':''} onClick={()=>setPeriod('weekly')}>本周回顾</button><button className={period==='monthly'?'active':''} onClick={()=>setPeriod('monthly')}>本月回顾</button></div><button className="primary" disabled={!!busy||!data.snapshot} onClick={()=>act('review',async()=>setDraft(await request('review',{period})))}><PencilLine size={19}/>生成阅读复盘</button></div><section className="review-overview"><div className="review-stats"><div><span>累计阅读与收听</span><strong>{valid?fmt(stats.totalSeconds):'待同步'}</strong></div><div><span>有效阅读天数</span><strong>{valid?(stats.readDays??'—'):'—'}<small> 天</small></strong></div><div><span>本机已保存回顾</span><strong>{data.reflections.length}<small> 次</small></strong></div></div><Rhythm period={stats} today={today} goal={data.settings.goal} expanded={period==='monthly'}/><p className="count-caption">统计更新时间：{stamp(stats?.fetchedAt)} · 每日达到 1 分钟计为有效阅读日</p></section><div className="review-bottom"><section><h2><CheckCircle size={22}/>读完，值得记一笔</h2><p className="muted small">仅展示有明确完成日期的本期记录。</p>{finished.length?finished.map(b=><div className="finished-row" key={b.id}><BookOpen size={20}/><span>{short(b.title)}</span><small>{b.finishDate}</small></div>):<p className="empty-inline">暂无已核对的本期完成日期，不代表没有读完。<br/>书架中的“已读完”仍可查看。</p>}</section><section><h2><Leaf size={22}/>留给下一次阅读</h2><p className="quiet-quote">不必急着读完所有的书。<br/>记住一句话，也是一种抵达。</p><button className="text-button" onClick={()=>go('shelf')}>挑选下一本主读 <ArrowRight size={17}/></button></section></div><SavedCards cards={data.cards.filter(c=>c.kind!=='card')} onOpen={setDraft}/></>;
}
